### ISSUE TITLE
Plans for {dupree} 0.3.x

### ISSUE THREAD

**Issue by russHyde** [russHyde/dupree#48]
Major
- [ ] - Provide a way to highlight, or print, the duplicated region corresponding to a match (#44 and #27)
- [x] - Introduce a lightweight class to store pairwise block-to-block duplication information (#60 ; see #63 )
- [ ] - Visualisation of duplication within a project
- [ ] - Provide some estimate of `lines-of-code-that-could-be-saved` (or similar) based on the dup-length and the frequency with which that dup is found across the files

Minor
- [x] - `dupree_package()` and `dupree_dir()` should work on current-working dir by default
- [x] - tests that directly use the top-level entry points, eg, make a package structure in a subdir of `/tests` and run `dupree`, `dupree_dir` and `dupree_package` on it (#45 )
- [x] - bump `min_block_size` to 40
- [ ] - fix `dupree_package` so that it assesses
    - [ ] -  the R subdirectory of a given directory, rather than any subdirectory of the given directory that contains `/R/` in it's name (found while running dupree_package on unitizer)
    - [x] - the structure of the passed-in directory (are DESCRIPTION, ~NAMESPACE~ and R/ all present?) #57 
- [ ] - `relative_path` argument in `dupree_dir` and `dupree_package` to indicate whether the filepaths in the results should be written relative to the analysed directory (vs, as full paths) and also whether excluded directories/files are specified relative to the analysed directory #62

**Comment by russHyde** [comment]
Plans moved to #69
